apiVersion: v1
kind: Pod
metadata:
  name: base64-pod
spec:
  volumes:
    - name: shared-bin
      emptyDir: {}

  containers:
    - name: base64-cli
      image: base64-cli:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /shared-bin
          name: shared-bin

    - name: sidecar
      image: sidecar:latest
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /shared-bin
          name: shared-bin
      command: ["/bin/sh", "-c", "cp /sidecar /shared-bin/sidecar && chmod +x /shared-bin/sidecar && sleep infinity"]
